[tasks.clippy]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.clippy-fix]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--fix",
	"--allow-dirty",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.fmt]
workspace = false
command = "bash"
args = [
	"-lc",
	"taplo fmt && cargo +nightly fmt --all",
]

[tasks.nextest]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.udeps]
workspace = false
command = "cargo"
toolchain = "nightly"
args = [
	"udeps",
	"--workspace",
	"--all-targets",
	"--all-features",
]
