#![deny(clippy::all, missing_docs, unused_crate_dependencies)]

//! BCP47 language tags.

// crates.io
#[cfg(feature = "serde")]
use serde::{
	de::{Deserializer, Error},
	ser::Serializer,
	Deserialize, Serialize,
};
// self
use Language::*;

/// Language collection.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Language {
	/// Afrikaans (South Africa)
	AfZa,
	/// Albanian (Albania)
	SqAl,
	/// Alsatian (France)
	GswFr,
	/// Amharic (Ethiopia)
	AmEt,
	/// Arabic (Algeria)
	ArDz,
	/// Arabic (Bahrain)
	ArBh,
	/// Arabic (Egypt)
	ArEg,
	/// Arabic (Iraq)
	ArIq,
	/// Arabic (Jordan)
	ArJo,
	/// Arabic (Kuwait)
	ArKw,
	/// Arabic (Lebanon)
	ArLb,
	/// Arabic (Libya)
	ArLy,
	/// Arabic (Morocco)
	ArMa,
	/// Arabic (Oman)
	ArOm,
	/// Arabic (Qatar)
	ArQa,
	/// Arabic (Saudi Arabia)
	ArSa,
	/// Arabic (Syria)
	ArSy,
	/// Arabic (Tunisia)
	ArTn,
	/// Arabic (U.A.E.)
	ArAe,
	/// Arabic (Yemen)
	ArYe,
	/// Armenian (Armenia)
	HyAm,
	/// Assamese (India)
	AsIn,
	/// Azerbaijani (Cyrillic, Azerbaijan)
	AzCyrlAz,
	/// Azerbaijani (Latin, Azerbaijan)
	AzLatnAz,
	/// Bangla (Bangladesh)
	BnBd,
	/// Bangla (India)
	BnIn,
	/// Bashkir (Russia)
	BaRu,
	/// Basque (Spain)
	EuEs,
	/// Belarusian (Belarus)
	BeBy,
	/// Bosnian (Cyrillic, Bosnia and Herzegovina)
	BsCyrlBa,
	/// Bosnian (Latin, Bosnia and Herzegovina)
	BsLatnBa,
	/// Breton (France)
	BrFr,
	/// Bulgarian (Bulgaria)
	BgBg,
	/// Burmese (Myanmar)
	MyMm,
	/// Catalan (Spain)
	CaEs,
	/// Central Atlas Tamazight (Arabic, Morocco)
	TzmArabMa,
	/// Central Kurdish (Iraq)
	KuArabIq,
	/// Cherokee (United States)
	ChrCherUs,
	/// Chinese (Simplified, People's Republic of China)
	ZhCn,
	/// Chinese (Simplified, Singapore)
	ZhSg,
	/// Chinese (Traditional, Hong Kong S.A.R.)
	ZhHk,
	/// Chinese (Traditional, Macao S.A.R.)
	ZhMo,
	/// Chinese (Traditional, Taiwan)
	ZhTw,
	/// Corsican (France)
	CoFr,
	/// Croatian (Croatia)
	HrHr,
	/// Croatian (Latin, Bosnia and Herzegovina)
	HrBa,
	/// Czech (Czech Republic)
	CsCz,
	/// Danish (Denmark)
	DaDk,
	/// Dari (Afghanistan)
	PrsAf,
	/// Divehi (Maldives)
	DvMv,
	/// Dutch (Belgium)
	NlBe,
	/// Dutch (Netherlands)
	NlNl,
	/// Dzongkha (Bhutan)
	DzBt,
	/// English (Australia)
	EnAu,
	/// English (Belize)
	EnBz,
	/// English (Canada)
	EnCa,
	/// English (Caribbean)
	En029,
	/// English (Hong Kong)
	EnHk,
	/// English (India)
	EnIn,
	/// English (Ireland)
	EnIe,
	/// English (Jamaica)
	EnJm,
	/// English (Malaysia)
	EnMy,
	/// English (New Zealand)
	EnNz,
	/// English (Republic of the Philippines)
	EnPh,
	/// English (Singapore)
	EnSg,
	/// English (South Africa)
	EnZa,
	/// English (Trinidad and Tobago)
	EnTt,
	/// English (United Arab Emirates)
	EnAe,
	/// English (United Kingdom)
	EnGb,
	/// English (United States)
	EnUs,
	/// English (Zimbabwe)
	EnZw,
	/// Estonian (Estonia)
	EtEe,
	/// Faroese (Faroe Islands)
	FoFo,
	/// Filipino (Philippines)
	FilPh,
	/// Finnish (Finland)
	FiFi,
	/// French (Belgium)
	FrBe,
	/// French (Côte d’Ivoire)
	FrCi,
	/// French (Cameroon)
	FrCm,
	/// French (Canada)
	FrCa,
	/// French (Caribbean)
	Fr029,
	/// French (Congo, DRC)
	FrCd,
	/// French (France)
	FrFr,
	/// French (Haiti)
	FrHt,
	/// French (Luxembourg)
	FrLu,
	/// French (Mali)
	FrMl,
	/// French (Morocco)
	FrMa,
	/// French (Principality of Monaco)
	FrMc,
	/// French (Réunion)
	FrRe,
	/// French (Senegal)
	FrSn,
	/// French (Switzerland)
	FrCh,
	/// Frisian (Netherlands)
	FyNl,
	/// Fulah (Latin, Nigeria)
	FfLatnNg,
	/// Fulah (Latin, Senegal)
	FfLatnSn,
	/// Galician (Spain)
	GlEs,
	/// Georgian (Georgia)
	KaGe,
	/// German (Austria)
	DeAt,
	/// German (Germany)
	DeDe,
	/// German (Liechtenstein)
	DeLi,
	/// German (Luxembourg)
	DeLu,
	/// German (Switzerland)
	DeCh,
	/// Greek (Greece)
	ElGr,
	/// Greenlandic (Greenland)
	KlGl,
	/// Guarani (Paraguay)
	GnPy,
	/// Gujarati (India)
	GuIn,
	/// Hausa (Latin, Nigeria)
	HaLatnNg,
	/// Hawaiian (United States)
	HawUs,
	/// Hebrew (Israel)
	HeIl,
	/// Hindi (India)
	HiIn,
	/// Hungarian (Hungary)
	HuHu,
	/// Icelandic (Iceland)
	IsIs,
	/// Igbo (Nigeria)
	IgNg,
	/// Indonesian (Indonesia)
	IdId,
	/// Inuktitut (Latin, Canada)
	IuLatnCa,
	/// Inuktitut (Syllabics, Canada)
	IuCansCa,
	/// Irish (Ireland)
	GaIe,
	/// Italian (Italy)
	ItIt,
	/// Italian (Switzerland)
	ItCh,
	/// Japanese (Japan)
	JaJp,
	/// Kannada (India)
	KnIn,
	/// Kanuri (Latin, Nigeria)
	KrLatnNg,
	/// Kashmiri (Devanagari, India)
	KsDevaIn,
	/// Kazakh (Kazakhstan)
	KkKz,
	/// Khmer (Cambodia)
	KmKh,
	/// K'iche (Latin, Guatemala)
	QucLatnGt,
	/// Kinyarwanda (Rwanda)
	RwRw,
	/// Kiswahili (Kenya)
	SwKe,
	/// Konkani (India)
	KokIn,
	/// Korean (Korea)
	KoKr,
	/// Kyrgyz (Kyrgyzstan)
	KyKg,
	/// Lao (Lao P.D.R.)
	LoLa,
	/// Latin (Vatican City)
	LaVa,
	/// Latvian (Latvia)
	LvLv,
	/// Lithuanian (Lithuania)
	LtLt,
	/// Lower Sorbian (Germany)
	DsbDe,
	/// Luxembourgish (Luxembourg)
	LbLu,
	/// Macedonian (North Macedonia)
	MkMk,
	/// Malay (Brunei Darussalam)
	MsBn,
	/// Malay (Malaysia)
	MsMy,
	/// Malayalam (India)
	MlIn,
	/// Maltese (Malta)
	MtMt,
	/// Maori (New Zealand)
	MiNz,
	/// Mapudungun (Chile)
	ArnCl,
	/// Marathi (India)
	MrIn,
	/// Mohawk (Canada)
	MohCa,
	/// Mongolian (Cyrillic, Mongolia)
	MnMn,
	/// Mongolian (Traditional Mongolian, Mongolia)
	MnMongMn,
	/// Nepali (India)
	NeIn,
	/// Nepali (Nepal)
	NeNp,
	/// Norwegian, Bokmål (Norway)
	NbNo,
	/// Norwegian, Nynorsk (Norway)
	NnNo,
	/// Occitan (France)
	OcFr,
	/// Odia (India)
	OrIn,
	/// Oromo (Ethiopia)
	OmEt,
	/// Pashto (Afghanistan)
	PsAf,
	/// Persian (Iran)
	FaIr,
	/// Polish (Poland)
	PlPl,
	/// Portuguese (Brazil)
	PtBr,
	/// Portuguese (Portugal)
	PtPt,
	/// Punjabi (India)
	PaIn,
	/// Punjabi (Islamic Republic of Pakistan)
	PaArabPk,
	/// Quechua (Bolivia)
	QuzBo,
	/// Quechua (Ecuador)
	QuzEc,
	/// Quechua (Peru)
	QuzPe,
	/// Romanian (Moldova)
	RoMd,
	/// Romanian (Romania)
	RoRo,
	/// Romansh (Switzerland)
	RmCh,
	/// Russian (Moldova)
	RuMd,
	/// Russian (Russia)
	RuRu,
	/// Sakha (Russia)
	SahRu,
	/// Sami, Inari (Finland)
	SmnFi,
	/// Sami, Lule (Norway)
	SmjNo,
	/// Sami, Lule (Sweden)
	SmjSe,
	/// Sami, Northern (Finland)
	SeFi,
	/// Sami, Northern (Norway)
	SeNo,
	/// Sami, Northern (Sweden)
	SeSe,
	/// Sami, Skolt (Finland)
	SmsFi,
	/// Sami, Southern (Norway)
	SmaNo,
	/// Sami, Southern (Sweden)
	SmaSe,
	/// Sanskrit (India)
	SaIn,
	/// Scottish Gaelic (United Kingdom)
	GdGb,
	/// Serbian (Cyrillic, Bosnia and Herzegovina)
	SrCyrlBa,
	/// Serbian (Cyrillic, Montenegro)
	SrCyrlMe,
	/// Serbian (Cyrillic, Serbia)
	SrCyrlRs,
	/// Serbian (Latin, Bosnia and Herzegovina)
	SrLatnBa,
	/// Serbian (Latin, Montenegro)
	SrLatnMe,
	/// Serbian (Latin, Serbia)
	SrLatnRs,
	/// Sesotho sa Leboa (South Africa)
	NsoZa,
	/// Setswana (Botswana)
	TnBw,
	/// Setswana (South Africa)
	TnZa,
	/// Sindhi (Islamic Republic of Pakistan)
	SdArabPk,
	/// Sinhala (Sri Lanka)
	SiLk,
	/// Slovak (Slovakia)
	SkSk,
	/// Slovenian (Slovenia)
	SlSi,
	/// Somali (Somalia)
	SoSo,
	/// Sotho (South Africa)
	StZa,
	/// Spanish (Argentina)
	EsAr,
	/// Spanish (Bolivarian Republic of Venezuela)
	EsVe,
	/// Spanish (Bolivia)
	EsBo,
	/// Spanish (Chile)
	EsCl,
	/// Spanish (Colombia)
	EsCo,
	/// Spanish (Costa Rica)
	EsCr,
	/// Spanish (Cuba)
	EsCu,
	/// Spanish (Dominican Republic)
	EsDo,
	/// Spanish (Ecuador)
	EsEc,
	/// Spanish (El Salvador)
	EsSv,
	/// Spanish (Guatemala)
	EsGt,
	/// Spanish (Honduras)
	EsHn,
	/// Spanish (Latin America)
	Es419,
	/// Spanish (Mexico)
	EsMx,
	/// Spanish (Nicaragua)
	EsNi,
	/// Spanish (Panama)
	EsPa,
	/// Spanish (Paraguay)
	EsPy,
	/// Spanish (Peru)
	EsPe,
	/// Spanish (Puerto Rico)
	EsPr,
	/// Spanish (Spain, International Sort)
	EsEs,
	/// Spanish (United States)
	EsUs,
	/// Spanish (Uruguay)
	EsUy,
	/// Swedish (Finland)
	SvFi,
	/// Swedish (Sweden)
	SvSe,
	/// Syriac (Syria)
	SyrSy,
	/// Tajik (Cyrillic, Tajikistan)
	TgCyrlTj,
	/// Tamazight (Latin, Algeria)
	TzmLatnDz,
	/// Tamil (India)
	TaIn,
	/// Tamil (Sri Lanka)
	TaLk,
	/// Tatar (Russia)
	TtRu,
	/// Telugu (India)
	TeIn,
	/// Thai (Thailand)
	ThTh,
	/// Tibetan (People's Republic of China)
	BoCn,
	/// Tigrinya (Eritrea)
	TiEr,
	/// Tigrinya (Ethiopia)
	TiEt,
	/// Tsonga (South Africa)
	TsZa,
	/// Turkish (Turkey)
	TrTr,
	/// Turkmen (Turkmenistan)
	TkTm,
	/// Ukrainian (Ukraine)
	UkUa,
	/// Upper Sorbian (Germany)
	HsbDe,
	/// Urdu (India)
	UrIn,
	/// Urdu (Islamic Republic of Pakistan)
	UrPk,
	/// Uyghur (People's Republic of China)
	UgCn,
	/// Uzbek (Cyrillic, Uzbekistan)
	UzCyrlUz,
	/// Uzbek (Latin, Uzbekistan)
	UzLatnUz,
	/// Valencian (Spain)
	CaEsValencia,
	/// Venda (South Africa)
	VeZa,
	/// Vietnamese (Vietnam)
	ViVn,
	/// Welsh (United Kingdom)
	CyGb,
	/// Wolof (Senegal)
	WoSn,
	/// Xhosa (South Africa)
	XhZa,
	/// Yi (People's Republic of China)
	IiCn,
	/// Yiddish (World)
	Yi001,
	/// Yoruba (Nigeria)
	YoNg,
	/// Zulu (South Africa)
	ZuZa,
}
impl Language {
	/// Get all languages.
	pub fn all() -> [Self; 250] {
		[
			AfZa,
			SqAl,
			GswFr,
			AmEt,
			ArDz,
			ArBh,
			ArEg,
			ArIq,
			ArJo,
			ArKw,
			ArLb,
			ArLy,
			ArMa,
			ArOm,
			ArQa,
			ArSa,
			ArSy,
			ArTn,
			ArAe,
			ArYe,
			HyAm,
			AsIn,
			AzCyrlAz,
			AzLatnAz,
			BnBd,
			BnIn,
			BaRu,
			EuEs,
			BeBy,
			BsCyrlBa,
			BsLatnBa,
			BrFr,
			BgBg,
			MyMm,
			CaEs,
			TzmArabMa,
			KuArabIq,
			ChrCherUs,
			ZhCn,
			ZhSg,
			ZhHk,
			ZhMo,
			ZhTw,
			CoFr,
			HrHr,
			HrBa,
			CsCz,
			DaDk,
			PrsAf,
			DvMv,
			NlBe,
			NlNl,
			DzBt,
			EnAu,
			EnBz,
			EnCa,
			En029,
			EnHk,
			EnIn,
			EnIe,
			EnJm,
			EnMy,
			EnNz,
			EnPh,
			EnSg,
			EnZa,
			EnTt,
			EnAe,
			EnGb,
			EnUs,
			EnZw,
			EtEe,
			FoFo,
			FilPh,
			FiFi,
			FrBe,
			FrCi,
			FrCm,
			FrCa,
			Fr029,
			FrCd,
			FrFr,
			FrHt,
			FrLu,
			FrMl,
			FrMa,
			FrMc,
			FrRe,
			FrSn,
			FrCh,
			FyNl,
			FfLatnNg,
			FfLatnSn,
			GlEs,
			KaGe,
			DeAt,
			DeDe,
			DeLi,
			DeLu,
			DeCh,
			ElGr,
			KlGl,
			GnPy,
			GuIn,
			HaLatnNg,
			HawUs,
			HeIl,
			HiIn,
			HuHu,
			IsIs,
			IgNg,
			IdId,
			IuLatnCa,
			IuCansCa,
			GaIe,
			ItIt,
			ItCh,
			JaJp,
			KnIn,
			KrLatnNg,
			KsDevaIn,
			KkKz,
			KmKh,
			QucLatnGt,
			RwRw,
			SwKe,
			KokIn,
			KoKr,
			KyKg,
			LoLa,
			LaVa,
			LvLv,
			LtLt,
			DsbDe,
			LbLu,
			MkMk,
			MsBn,
			MsMy,
			MlIn,
			MtMt,
			MiNz,
			ArnCl,
			MrIn,
			MohCa,
			MnMn,
			MnMongMn,
			NeIn,
			NeNp,
			NbNo,
			NnNo,
			OcFr,
			OrIn,
			OmEt,
			PsAf,
			FaIr,
			PlPl,
			PtBr,
			PtPt,
			PaIn,
			PaArabPk,
			QuzBo,
			QuzEc,
			QuzPe,
			RoMd,
			RoRo,
			RmCh,
			RuMd,
			RuRu,
			SahRu,
			SmnFi,
			SmjNo,
			SmjSe,
			SeFi,
			SeNo,
			SeSe,
			SmsFi,
			SmaNo,
			SmaSe,
			SaIn,
			GdGb,
			SrCyrlBa,
			SrCyrlMe,
			SrCyrlRs,
			SrLatnBa,
			SrLatnMe,
			SrLatnRs,
			NsoZa,
			TnBw,
			TnZa,
			SdArabPk,
			SiLk,
			SkSk,
			SlSi,
			SoSo,
			StZa,
			EsAr,
			EsVe,
			EsBo,
			EsCl,
			EsCo,
			EsCr,
			EsCu,
			EsDo,
			EsEc,
			EsSv,
			EsGt,
			EsHn,
			Es419,
			EsMx,
			EsNi,
			EsPa,
			EsPy,
			EsPe,
			EsPr,
			EsEs,
			EsUs,
			EsUy,
			SvFi,
			SvSe,
			SyrSy,
			TgCyrlTj,
			TzmLatnDz,
			TaIn,
			TaLk,
			TtRu,
			TeIn,
			ThTh,
			BoCn,
			TiEr,
			TiEt,
			TsZa,
			TrTr,
			TkTm,
			UkUa,
			HsbDe,
			UrIn,
			UrPk,
			UgCn,
			UzCyrlUz,
			UzLatnUz,
			CaEsValencia,
			VeZa,
			ViVn,
			CyGb,
			WoSn,
			XhZa,
			IiCn,
			Yi001,
			YoNg,
			ZuZa,
		]
	}

	/// Get the language tag.
	pub fn as_tag(&self) -> &'static str {
		match self {
			AfZa => "af-ZA",
			SqAl => "sq-AL",
			GswFr => "gsw-FR",
			AmEt => "am-ET",
			ArDz => "ar-DZ",
			ArBh => "ar-BH",
			ArEg => "ar-EG",
			ArIq => "ar-IQ",
			ArJo => "ar-JO",
			ArKw => "ar-KW",
			ArLb => "ar-LB",
			ArLy => "ar-LY",
			ArMa => "ar-MA",
			ArOm => "ar-OM",
			ArQa => "ar-QA",
			ArSa => "ar-SA",
			ArSy => "ar-SY",
			ArTn => "ar-TN",
			ArAe => "ar-AE",
			ArYe => "ar-YE",
			HyAm => "hy-AM",
			AsIn => "as-IN",
			AzCyrlAz => "az-Cyrl-AZ",
			AzLatnAz => "az-Latn-AZ",
			BnBd => "bn-BD",
			BnIn => "bn-IN",
			BaRu => "ba-RU",
			EuEs => "eu-ES",
			BeBy => "be-BY",
			BsCyrlBa => "bs-Cyrl-BA",
			BsLatnBa => "bs-Latn-BA",
			BrFr => "br-FR",
			BgBg => "bg-BG",
			MyMm => "my-MM",
			CaEs => "ca-ES",
			TzmArabMa => "tzm-Arab-MA",
			KuArabIq => "ku-Arab-IQ",
			ChrCherUs => "chr-Cher-US",
			ZhCn => "zh-CN",
			ZhSg => "zh-SG",
			ZhHk => "zh-HK",
			ZhMo => "zh-MO",
			ZhTw => "zh-TW",
			CoFr => "co-FR",
			HrHr => "hr-HR",
			HrBa => "hr-BA",
			CsCz => "cs-CZ",
			DaDk => "da-DK",
			PrsAf => "prs-AF",
			DvMv => "dv-MV",
			NlBe => "nl-BE",
			NlNl => "nl-NL",
			DzBt => "dz-BT",
			EnAu => "en-AU",
			EnBz => "en-BZ",
			EnCa => "en-CA",
			En029 => "en-029",
			EnHk => "en-HK",
			EnIn => "en-IN",
			EnIe => "en-IE",
			EnJm => "en-JM",
			EnMy => "en-MY",
			EnNz => "en-NZ",
			EnPh => "en-PH",
			EnSg => "en-SG",
			EnZa => "en-ZA",
			EnTt => "en-TT",
			EnAe => "en-AE",
			EnGb => "en-GB",
			EnUs => "en-US",
			EnZw => "en-ZW",
			EtEe => "et-EE",
			FoFo => "fo-FO",
			FilPh => "fil-PH",
			FiFi => "fi-FI",
			FrBe => "fr-BE",
			FrCi => "fr-CI",
			FrCm => "fr-CM",
			FrCa => "fr-CA",
			Fr029 => "fr-029",
			FrCd => "fr-CD",
			FrFr => "fr-FR",
			FrHt => "fr-HT",
			FrLu => "fr-LU",
			FrMl => "fr-ML",
			FrMa => "fr-MA",
			FrMc => "fr-MC",
			FrRe => "fr-RE",
			FrSn => "fr-SN",
			FrCh => "fr-CH",
			FyNl => "fy-NL",
			FfLatnNg => "ff-Latn-NG",
			FfLatnSn => "ff-Latn-SN",
			GlEs => "gl-ES",
			KaGe => "ka-GE",
			DeAt => "de-AT",
			DeDe => "de-DE",
			DeLi => "de-LI",
			DeLu => "de-LU",
			DeCh => "de-CH",
			ElGr => "el-GR",
			KlGl => "kl-GL",
			GnPy => "gn-PY",
			GuIn => "gu-IN",
			HaLatnNg => "ha-Latn-NG",
			HawUs => "haw-US",
			HeIl => "he-IL",
			HiIn => "hi-IN",
			HuHu => "hu-HU",
			IsIs => "is-IS",
			IgNg => "ig-NG",
			IdId => "id-ID",
			IuLatnCa => "iu-Latn-CA",
			IuCansCa => "iu-Cans-CA",
			GaIe => "ga-IE",
			ItIt => "it-IT",
			ItCh => "it-CH",
			JaJp => "ja-JP",
			KnIn => "kn-IN",
			KrLatnNg => "kr-Latn-NG",
			KsDevaIn => "ks-Deva-IN",
			KkKz => "kk-KZ",
			KmKh => "km-KH",
			QucLatnGt => "quc-Latn-GT",
			RwRw => "rw-RW",
			SwKe => "sw-KE",
			KokIn => "kok-IN",
			KoKr => "ko-KR",
			KyKg => "ky-KG",
			LoLa => "lo-LA",
			LaVa => "la-VA",
			LvLv => "lv-LV",
			LtLt => "lt-LT",
			DsbDe => "dsb-DE",
			LbLu => "lb-LU",
			MkMk => "mk-MK",
			MsBn => "ms-BN",
			MsMy => "ms-MY",
			MlIn => "ml-IN",
			MtMt => "mt-MT",
			MiNz => "mi-NZ",
			ArnCl => "arn-CL",
			MrIn => "mr-IN",
			MohCa => "moh-CA",
			MnMn => "mn-Cyrl-MN",
			MnMongMn => "mn-Mong-MN",
			NeIn => "ne-IN",
			NeNp => "ne-NP",
			NbNo => "nb-NO",
			NnNo => "nn-NO",
			OcFr => "oc-FR",
			OrIn => "or-IN",
			OmEt => "om-ET",
			PsAf => "ps-AF",
			FaIr => "fa-IR",
			PlPl => "pl-PL",
			PtBr => "pt-BR",
			PtPt => "pt-PT",
			PaIn => "pa-IN",
			PaArabPk => "pa-Arab-PK",
			QuzBo => "quz-BO",
			QuzEc => "quz-EC",
			QuzPe => "quz-PE",
			RoMd => "ro-MD",
			RoRo => "ro-RO",
			RmCh => "rm-CH",
			RuMd => "ru-MD",
			RuRu => "ru-RU",
			SahRu => "sah-RU",
			SmnFi => "smn-FI",
			SmjNo => "smj-NO",
			SmjSe => "smj-SE",
			SeFi => "se-FI",
			SeNo => "se-NO",
			SeSe => "se-SE",
			SmsFi => "sms-FI",
			SmaNo => "sma-NO",
			SmaSe => "sma-SE",
			SaIn => "sa-IN",
			GdGb => "gd-GB",
			SrCyrlBa => "sr-Cyrl-BA",
			SrCyrlMe => "sr-Cyrl-ME",
			SrCyrlRs => "sr-Cyrl-RS",
			SrLatnBa => "sr-Latn-BA",
			SrLatnMe => "sr-Latn-ME",
			SrLatnRs => "sr-Latn-RS",
			NsoZa => "nso-ZA",
			TnBw => "tn-BW",
			TnZa => "tn-ZA",
			SdArabPk => "sd-Arab-PK",
			SiLk => "si-LK",
			SkSk => "sk-SK",
			SlSi => "sl-SI",
			SoSo => "so-SO",
			StZa => "st-ZA",
			EsAr => "es-AR",
			EsVe => "es-VE",
			EsBo => "es-BO",
			EsCl => "es-CL",
			EsCo => "es-CO",
			EsCr => "es-CR",
			EsCu => "es-CU",
			EsDo => "es-DO",
			EsEc => "es-EC",
			EsSv => "es-SV",
			EsGt => "es-GT",
			EsHn => "es-HN",
			Es419 => "es-419",
			EsMx => "es-MX",
			EsNi => "es-NI",
			EsPa => "es-PA",
			EsPy => "es-PY",
			EsPe => "es-PE",
			EsPr => "es-PR",
			EsEs => "es-ES",
			EsUs => "es-US",
			EsUy => "es-UY",
			SvFi => "sv-FI",
			SvSe => "sv-SE",
			SyrSy => "syr-SY",
			TgCyrlTj => "tg-Cyrl-TJ",
			TzmLatnDz => "tzm-Latn-DZ",
			TaIn => "ta-IN",
			TaLk => "ta-LK",
			TtRu => "tt-RU",
			TeIn => "te-IN",
			ThTh => "th-TH",
			BoCn => "bo-CN",
			TiEr => "ti-ER",
			TiEt => "ti-ET",
			TsZa => "ts-ZA",
			TrTr => "tr-TR",
			TkTm => "tk-TM",
			UkUa => "uk-UA",
			HsbDe => "hsb-DE",
			UrIn => "ur-IN",
			UrPk => "ur-PK",
			UgCn => "ug-CN",
			UzCyrlUz => "uz-Cyrl-UZ",
			UzLatnUz => "uz-Latn-UZ",
			CaEsValencia => "ca-ES-VALENCIA",
			VeZa => "ve-ZA",
			ViVn => "vi-VN",
			CyGb => "cy-GB",
			WoSn => "wo-SN",
			XhZa => "xh-ZA",
			IiCn => "ii-CN",
			Yi001 => "yi-001",
			YoNg => "yo-NG",
			ZuZa => "zu-ZA",
		}
	}

	/// Parse a language tag.
	pub fn from_tag(tag: &str) -> Option<Self> {
		Some(match tag {
			"af-ZA" => AfZa,
			"sq-AL" => SqAl,
			"gsw-FR" => GswFr,
			"am-ET" => AmEt,
			"ar-DZ" => ArDz,
			"ar-BH" => ArBh,
			"ar-EG" => ArEg,
			"ar-IQ" => ArIq,
			"ar-JO" => ArJo,
			"ar-KW" => ArKw,
			"ar-LB" => ArLb,
			"ar-LY" => ArLy,
			"ar-MA" => ArMa,
			"ar-OM" => ArOm,
			"ar-QA" => ArQa,
			"ar-SA" => ArSa,
			"ar-SY" => ArSy,
			"ar-TN" => ArTn,
			"ar-AE" => ArAe,
			"ar-YE" => ArYe,
			"hy-AM" => HyAm,
			"as-IN" => AsIn,
			"az-Cyrl-AZ" => AzCyrlAz,
			"az-Latn-AZ" => AzLatnAz,
			"bn-BD" => BnBd,
			"bn-IN" => BnIn,
			"ba-RU" => BaRu,
			"eu-ES" => EuEs,
			"be-BY" => BeBy,
			"bs-Cyrl-BA" => BsCyrlBa,
			"bs-Latn-BA" => BsLatnBa,
			"br-FR" => BrFr,
			"bg-BG" => BgBg,
			"my-MM" => MyMm,
			"ca-ES" => CaEs,
			"tzm-Arab-MA" => TzmArabMa,
			"ku-Arab-IQ" => KuArabIq,
			"chr-Cher-US" => ChrCherUs,
			"zh-CN" => ZhCn,
			"zh-SG" => ZhSg,
			"zh-HK" => ZhHk,
			"zh-MO" => ZhMo,
			"zh-TW" => ZhTw,
			"co-FR" => CoFr,
			"hr-HR" => HrHr,
			"hr-BA" => HrBa,
			"cs-CZ" => CsCz,
			"da-DK" => DaDk,
			"prs-AF" => PrsAf,
			"dv-MV" => DvMv,
			"nl-BE" => NlBe,
			"nl-NL" => NlNl,
			"dz-BT" => DzBt,
			"en-AU" => EnAu,
			"en-BZ" => EnBz,
			"en-CA" => EnCa,
			"en-029" => En029,
			"en-HK" => EnHk,
			"en-IN" => EnIn,
			"en-IE" => EnIe,
			"en-JM" => EnJm,
			"en-MY" => EnMy,
			"en-NZ" => EnNz,
			"en-PH" => EnPh,
			"en-SG" => EnSg,
			"en-ZA" => EnZa,
			"en-TT" => EnTt,
			"en-AE" => EnAe,
			"en-GB" => EnGb,
			"en-US" => EnUs,
			"en-ZW" => EnZw,
			"et-EE" => EtEe,
			"fo-FO" => FoFo,
			"fil-PH" => FilPh,
			"fi-FI" => FiFi,
			"fr-BE" => FrBe,
			"fr-CI" => FrCi,
			"fr-CM" => FrCm,
			"fr-CA" => FrCa,
			"fr-029" => Fr029,
			"fr-CD" => FrCd,
			"fr-FR" => FrFr,
			"fr-HT" => FrHt,
			"fr-LU" => FrLu,
			"fr-ML" => FrMl,
			"fr-MA" => FrMa,
			"fr-MC" => FrMc,
			"fr-RE" => FrRe,
			"fr-SN" => FrSn,
			"fr-CH" => FrCh,
			"fy-NL" => FyNl,
			"ff-Latn-NG" => FfLatnNg,
			"ff-Latn-SN" => FfLatnSn,
			"gl-ES" => GlEs,
			"ka-GE" => KaGe,
			"de-AT" => DeAt,
			"de-DE" => DeDe,
			"de-LI" => DeLi,
			"de-LU" => DeLu,
			"de-CH" => DeCh,
			"el-GR" => ElGr,
			"kl-GL" => KlGl,
			"gn-PY" => GnPy,
			"gu-IN" => GuIn,
			"ha-Latn-NG" => HaLatnNg,
			"haw-US" => HawUs,
			"he-IL" => HeIl,
			"hi-IN" => HiIn,
			"hu-HU" => HuHu,
			"is-IS" => IsIs,
			"ig-NG" => IgNg,
			"id-ID" => IdId,
			"iu-Latn-CA" => IuLatnCa,
			"iu-Cans-CA" => IuCansCa,
			"ga-IE" => GaIe,
			"it-IT" => ItIt,
			"it-CH" => ItCh,
			"ja-JP" => JaJp,
			"kn-IN" => KnIn,
			"kr-Latn-NG" => KrLatnNg,
			"ks-Deva-IN" => KsDevaIn,
			"kk-KZ" => KkKz,
			"km-KH" => KmKh,
			"quc-Latn-GT" => QucLatnGt,
			"rw-RW" => RwRw,
			"sw-KE" => SwKe,
			"kok-IN" => KokIn,
			"ko-KR" => KoKr,
			"ky-KG" => KyKg,
			"lo-LA" => LoLa,
			"la-VA" => LaVa,
			"lv-LV" => LvLv,
			"lt-LT" => LtLt,
			"dsb-DE" => DsbDe,
			"lb-LU" => LbLu,
			"mk-MK" => MkMk,
			"ms-BN" => MsBn,
			"ms-MY" => MsMy,
			"ml-IN" => MlIn,
			"mt-MT" => MtMt,
			"mi-NZ" => MiNz,
			"arn-CL" => ArnCl,
			"mr-IN" => MrIn,
			"moh-CA" => MohCa,
			"mn-Cyrl-MN" => MnMn,
			"mn-Mong-MN" => MnMongMn,
			"ne-IN" => NeIn,
			"ne-NP" => NeNp,
			"nb-NO" => NbNo,
			"nn-NO" => NnNo,
			"oc-FR" => OcFr,
			"or-IN" => OrIn,
			"om-ET" => OmEt,
			"ps-AF" => PsAf,
			"fa-IR" => FaIr,
			"pl-PL" => PlPl,
			"pt-BR" => PtBr,
			"pt-PT" => PtPt,
			"pa-IN" => PaIn,
			"pa-Arab-PK" => PaArabPk,
			"quz-BO" => QuzBo,
			"quz-EC" => QuzEc,
			"quz-PE" => QuzPe,
			"ro-MD" => RoMd,
			"ro-RO" => RoRo,
			"rm-CH" => RmCh,
			"ru-MD" => RuMd,
			"ru-RU" => RuRu,
			"sah-RU" => SahRu,
			"smn-FI" => SmnFi,
			"smj-NO" => SmjNo,
			"smj-SE" => SmjSe,
			"se-FI" => SeFi,
			"se-NO" => SeNo,
			"se-SE" => SeSe,
			"sms-FI" => SmsFi,
			"sma-NO" => SmaNo,
			"sma-SE" => SmaSe,
			"sa-IN" => SaIn,
			"gd-GB" => GdGb,
			"sr-Cyrl-BA" => SrCyrlBa,
			"sr-Cyrl-ME" => SrCyrlMe,
			"sr-Cyrl-RS" => SrCyrlRs,
			"sr-Latn-BA" => SrLatnBa,
			"sr-Latn-ME" => SrLatnMe,
			"sr-Latn-RS" => SrLatnRs,
			"nso-ZA" => NsoZa,
			"tn-BW" => TnBw,
			"tn-ZA" => TnZa,
			"sd-Arab-PK" => SdArabPk,
			"si-LK" => SiLk,
			"sk-SK" => SkSk,
			"sl-SI" => SlSi,
			"so-SO" => SoSo,
			"st-ZA" => StZa,
			"es-AR" => EsAr,
			"es-VE" => EsVe,
			"es-BO" => EsBo,
			"es-CL" => EsCl,
			"es-CO" => EsCo,
			"es-CR" => EsCr,
			"es-CU" => EsCu,
			"es-DO" => EsDo,
			"es-EC" => EsEc,
			"es-SV" => EsSv,
			"es-GT" => EsGt,
			"es-HN" => EsHn,
			"es-419" => Es419,
			"es-MX" => EsMx,
			"es-NI" => EsNi,
			"es-PA" => EsPa,
			"es-PY" => EsPy,
			"es-PE" => EsPe,
			"es-PR" => EsPr,
			"es-ES" => EsEs,
			"es-US" => EsUs,
			"es-UY" => EsUy,
			"sv-FI" => SvFi,
			"sv-SE" => SvSe,
			"syr-SY" => SyrSy,
			"tg-Cyrl-TJ" => TgCyrlTj,
			"tzm-Latn-DZ" => TzmLatnDz,
			"ta-IN" => TaIn,
			"ta-LK" => TaLk,
			"tt-RU" => TtRu,
			"te-IN" => TeIn,
			"th-TH" => ThTh,
			"bo-CN" => BoCn,
			"ti-ER" => TiEr,
			"ti-ET" => TiEt,
			"ts-ZA" => TsZa,
			"tr-TR" => TrTr,
			"tk-TM" => TkTm,
			"uk-UA" => UkUa,
			"hsb-DE" => HsbDe,
			"ur-IN" => UrIn,
			"ur-PK" => UrPk,
			"ug-CN" => UgCn,
			"uz-Cyrl-UZ" => UzCyrlUz,
			"uz-Latn-UZ" => UzLatnUz,
			"ca-ES-VALENCIA" => CaEsValencia,
			"ve-ZA" => VeZa,
			"vi-VN" => ViVn,
			"cy-GB" => CyGb,
			"wo-SN" => WoSn,
			"xh-ZA" => XhZa,
			"ii-CN" => IiCn,
			"yi-001" => Yi001,
			"yo-NG" => YoNg,
			"zu-ZA" => ZuZa,
			_ => return None,
		})
	}

	/// Get the language name.
	pub fn as_str(&self) -> &str {
		match self {
			AfZa => "Afrikaans (South Africa)",
			SqAl => "Albanian (Albania)",
			GswFr => "Alsatian (France)",
			AmEt => "Amharic (Ethiopia)",
			ArDz => "Arabic (Algeria)",
			ArBh => "Arabic (Bahrain)",
			ArEg => "Arabic (Egypt)",
			ArIq => "Arabic (Iraq)",
			ArJo => "Arabic (Jordan)",
			ArKw => "Arabic (Kuwait)",
			ArLb => "Arabic (Lebanon)",
			ArLy => "Arabic (Libya)",
			ArMa => "Arabic (Morocco)",
			ArOm => "Arabic (Oman)",
			ArQa => "Arabic (Qatar)",
			ArSa => "Arabic (Saudi Arabia)",
			ArSy => "Arabic (Syria)",
			ArTn => "Arabic (Tunisia)",
			ArAe => "Arabic (U.A.E.)",
			ArYe => "Arabic (Yemen)",
			HyAm => "Armenian (Armenia)",
			AsIn => "Assamese (India)",
			AzCyrlAz => "Azerbaijani (Cyrillic, Azerbaijan)",
			AzLatnAz => "Azerbaijani (Latin, Azerbaijan)",
			BnBd => "Bangla (Bangladesh)",
			BnIn => "Bangla (India)",
			BaRu => "Bashkir (Russia)",
			EuEs => "Basque (Spain)",
			BeBy => "Belarusian (Belarus)",
			BsCyrlBa => "Bosnian (Cyrillic, Bosnia and Herzegovina)",
			BsLatnBa => "Bosnian (Latin, Bosnia and Herzegovina)",
			BrFr => "Breton (France)",
			BgBg => "Bulgarian (Bulgaria)",
			MyMm => "Burmese (Myanmar)",
			CaEs => "Catalan (Spain)",
			TzmArabMa => "Central Atlas Tamazight (Arabic, Morocco)",
			KuArabIq => "Central Kurdish (Iraq)",
			ChrCherUs => "Cherokee (United States)",
			ZhCn => "Chinese (Simplified, People's Republic of China)",
			ZhSg => "Chinese (Simplified, Singapore)",
			ZhHk => "Chinese (Traditional, Hong Kong S.A.R.)",
			ZhMo => "Chinese (Traditional, Macao S.A.R.)",
			ZhTw => "Chinese (Traditional, Taiwan)",
			CoFr => "Corsican (France)",
			HrHr => "Croatian (Croatia)",
			HrBa => "Croatian (Latin, Bosnia and Herzegovina)",
			CsCz => "Czech (Czech Republic)",
			DaDk => "Danish (Denmark)",
			PrsAf => "Dari (Afghanistan)",
			DvMv => "Divehi (Maldives)",
			NlBe => "Dutch (Belgium)",
			NlNl => "Dutch (Netherlands)",
			DzBt => "Dzongkha (Bhutan)",
			EnAu => "English (Australia)",
			EnBz => "English (Belize)",
			EnCa => "English (Canada)",
			En029 => "English (Caribbean)",
			EnHk => "English (Hong Kong)",
			EnIn => "English (India)",
			EnIe => "English (Ireland)",
			EnJm => "English (Jamaica)",
			EnMy => "English (Malaysia)",
			EnNz => "English (New Zealand)",
			EnPh => "English (Republic of the Philippines)",
			EnSg => "English (Singapore)",
			EnZa => "English (South Africa)",
			EnTt => "English (Trinidad and Tobago)",
			EnAe => "English (United Arab Emirates)",
			EnGb => "English (United Kingdom)",
			EnUs => "English (United States)",
			EnZw => "English (Zimbabwe)",
			EtEe => "Estonian (Estonia)",
			FoFo => "Faroese (Faroe Islands)",
			FilPh => "Filipino (Philippines)",
			FiFi => "Finnish (Finland)",
			FrBe => "French (Belgium)",
			FrCi => "French (Côte d’Ivoire)",
			FrCm => "French (Cameroon)",
			FrCa => "French (Canada)",
			Fr029 => "French (Caribbean)",
			FrCd => "French (Congo, DRC)",
			FrFr => "French (France)",
			FrHt => "French (Haiti)",
			FrLu => "French (Luxembourg)",
			FrMl => "French (Mali)",
			FrMa => "French (Morocco)",
			FrMc => "French (Principality of Monaco)",
			FrRe => "French (Réunion)",
			FrSn => "French (Senegal)",
			FrCh => "French (Switzerland)",
			FyNl => "Frisian (Netherlands)",
			FfLatnNg => "Fulah (Latin, Nigeria)",
			FfLatnSn => "Fulah (Latin, Senegal)",
			GlEs => "Galician (Spain)",
			KaGe => "Georgian (Georgia)",
			DeAt => "German (Austria)",
			DeDe => "German (Germany)",
			DeLi => "German (Liechtenstein)",
			DeLu => "German (Luxembourg)",
			DeCh => "German (Switzerland)",
			ElGr => "Greek (Greece)",
			KlGl => "Greenlandic (Greenland)",
			GnPy => "Guarani (Paraguay)",
			GuIn => "Gujarati (India)",
			HaLatnNg => "Hausa (Latin, Nigeria)",
			HawUs => "Hawaiian (United States)",
			HeIl => "Hebrew (Israel)",
			HiIn => "Hindi (India)",
			HuHu => "Hungarian (Hungary)",
			IsIs => "Icelandic (Iceland)",
			IgNg => "Igbo (Nigeria)",
			IdId => "Indonesian (Indonesia)",
			IuLatnCa => "Inuktitut (Latin, Canada)",
			IuCansCa => "Inuktitut (Syllabics, Canada)",
			GaIe => "Irish (Ireland)",
			ItIt => "Italian (Italy)",
			ItCh => "Italian (Switzerland)",
			JaJp => "Japanese (Japan)",
			KnIn => "Kannada (India)",
			KrLatnNg => "Kanuri (Latin, Nigeria)",
			KsDevaIn => "Kashmiri (Devanagari, India)",
			KkKz => "Kazakh (Kazakhstan)",
			KmKh => "Khmer (Cambodia)",
			QucLatnGt => "K'iche (Latin, Guatemala)",
			RwRw => "Kinyarwanda (Rwanda)",
			SwKe => "Kiswahili (Kenya)",
			KokIn => "Konkani (India)",
			KoKr => "Korean (Korea)",
			KyKg => "Kyrgyz (Kyrgyzstan)",
			LoLa => "Lao (Lao P.D.R.)",
			LaVa => "Latin (Vatican City)",
			LvLv => "Latvian (Latvia)",
			LtLt => "Lithuanian (Lithuania)",
			DsbDe => "Lower Sorbian (Germany)",
			LbLu => "Luxembourgish (Luxembourg)",
			MkMk => "Macedonian (North Macedonia)",
			MsBn => "Malay (Brunei Darussalam)",
			MsMy => "Malay (Malaysia)",
			MlIn => "Malayalam (India)",
			MtMt => "Maltese (Malta)",
			MiNz => "Maori (New Zealand)",
			ArnCl => "Mapudungun (Chile)",
			MrIn => "Marathi (India)",
			MohCa => "Mohawk (Canada)",
			MnMn => "Mongolian (Cyrillic, Mongolia)",
			MnMongMn => "Mongolian (Traditional Mongolian, Mongolia)",
			NeIn => "Nepali (India)",
			NeNp => "Nepali (Nepal)",
			NbNo => "Norwegian, Bokmål (Norway)",
			NnNo => "Norwegian, Nynorsk (Norway)",
			OcFr => "Occitan (France)",
			OrIn => "Odia (India)",
			OmEt => "Oromo (Ethiopia)",
			PsAf => "Pashto (Afghanistan)",
			FaIr => "Persian (Iran)",
			PlPl => "Polish (Poland)",
			PtBr => "Portuguese (Brazil)",
			PtPt => "Portuguese (Portugal)",
			PaIn => "Punjabi (India)",
			PaArabPk => "Punjabi (Islamic Republic of Pakistan)",
			QuzBo => "Quechua (Bolivia)",
			QuzEc => "Quechua (Ecuador)",
			QuzPe => "Quechua (Peru)",
			RoMd => "Romanian (Moldova)",
			RoRo => "Romanian (Romania)",
			RmCh => "Romansh (Switzerland)",
			RuMd => "Russian (Moldova)",
			RuRu => "Russian (Russia)",
			SahRu => "Sakha (Russia)",
			SmnFi => "Sami, Inari (Finland)",
			SmjNo => "Sami, Lule (Norway)",
			SmjSe => "Sami, Lule (Sweden)",
			SeFi => "Sami, Northern (Finland)",
			SeNo => "Sami, Northern (Norway)",
			SeSe => "Sami, Northern (Sweden)",
			SmsFi => "Sami, Skolt (Finland)",
			SmaNo => "Sami, Southern (Norway)",
			SmaSe => "Sami, Southern (Sweden)",
			SaIn => "Sanskrit (India)",
			GdGb => "Scottish Gaelic (United Kingdom)",
			SrCyrlBa => "Serbian (Cyrillic, Bosnia and Herzegovina)",
			SrCyrlMe => "Serbian (Cyrillic, Montenegro)",
			SrCyrlRs => "Serbian (Cyrillic, Serbia)",
			SrLatnBa => "Serbian (Latin, Bosnia and Herzegovina)",
			SrLatnMe => "Serbian (Latin, Montenegro)",
			SrLatnRs => "Serbian (Latin, Serbia)",
			NsoZa => "Sesotho sa Leboa (South Africa)",
			TnBw => "Setswana (Botswana)",
			TnZa => "Setswana (South Africa)",
			SdArabPk => "Sindhi (Islamic Republic of Pakistan)",
			SiLk => "Sinhala (Sri Lanka)",
			SkSk => "Slovak (Slovakia)",
			SlSi => "Slovenian (Slovenia)",
			SoSo => "Somali (Somalia)",
			StZa => "Sotho (South Africa)",
			EsAr => "Spanish (Argentina)",
			EsVe => "Spanish (Bolivarian Republic of Venezuela)",
			EsBo => "Spanish (Bolivia)",
			EsCl => "Spanish (Chile)",
			EsCo => "Spanish (Colombia)",
			EsCr => "Spanish (Costa Rica)",
			EsCu => "Spanish (Cuba)",
			EsDo => "Spanish (Dominican Republic)",
			EsEc => "Spanish (Ecuador)",
			EsSv => "Spanish (El Salvador)",
			EsGt => "Spanish (Guatemala)",
			EsHn => "Spanish (Honduras)",
			Es419 => "Spanish (Latin America)",
			EsMx => "Spanish (Mexico)",
			EsNi => "Spanish (Nicaragua)",
			EsPa => "Spanish (Panama)",
			EsPy => "Spanish (Paraguay)",
			EsPe => "Spanish (Peru)",
			EsPr => "Spanish (Puerto Rico)",
			EsEs => "Spanish (Spain, International Sort)",
			EsUs => "Spanish (United States)",
			EsUy => "Spanish (Uruguay)",
			SvFi => "Swedish (Finland)",
			SvSe => "Swedish (Sweden)",
			SyrSy => "Syriac (Syria)",
			TgCyrlTj => "Tajik (Cyrillic, Tajikistan)",
			TzmLatnDz => "Tamazight (Latin, Algeria)",
			TaIn => "Tamil (India)",
			TaLk => "Tamil (Sri Lanka)",
			TtRu => "Tatar (Russia)",
			TeIn => "Telugu (India)",
			ThTh => "Thai (Thailand)",
			BoCn => "Tibetan (People's Republic of China)",
			TiEr => "Tigrinya (Eritrea)",
			TiEt => "Tigrinya (Ethiopia)",
			TsZa => "Tsonga (South Africa)",
			TrTr => "Turkish (Turkey)",
			TkTm => "Turkmen (Turkmenistan)",
			UkUa => "Ukrainian (Ukraine)",
			HsbDe => "Upper Sorbian (Germany)",
			UrIn => "Urdu (India)",
			UrPk => "Urdu (Islamic Republic of Pakistan)",
			UgCn => "Uyghur (People's Republic of China)",
			UzCyrlUz => "Uzbek (Cyrillic, Uzbekistan)",
			UzLatnUz => "Uzbek (Latin, Uzbekistan)",
			CaEsValencia => "Valencian (Spain)",
			VeZa => "Venda (South Africa)",
			ViVn => "Vietnamese (Vietnam)",
			CyGb => "Welsh (United Kingdom)",
			WoSn => "Wolof (Senegal)",
			XhZa => "Xhosa (South Africa)",
			IiCn => "Yi (People's Republic of China)",
			Yi001 => "Yiddish (World)",
			YoNg => "Yoruba (Nigeria)",
			ZuZa => "Zulu (South Africa)",
		}
	}

	/// Get the language name in the language itself.
	pub fn as_local(&self) -> &'static str {
		match self {
			AfZa => "Afrikaans (Suid-Afrika)",
			SqAl => "Shqip (Shqipëri)",
			GswFr => "Elsässisch (Frankreich)",
			AmEt => "አማርኛ (ኢትዮጵያ)",
			ArDz => "العربية (الجزائر)",
			ArBh => "العربية (البحرين)",
			ArEg => "العربية (مصر)",
			ArIq => "العربية (العراق)",
			ArJo => "العربية (الأردن)",
			ArKw => "العربية (الكويت)",
			ArLb => "العربية (لبنان)",
			ArLy => "العربية (ليبيا)",
			ArMa => "العربية (المغرب)",
			ArOm => "العربية (عمان)",
			ArQa => "العربية (قطر)",
			ArSa => "العربية (المملكة العربية السعودية)",
			ArSy => "العربية (سوريا)",
			ArTn => "العربية (تونس)",
			ArAe => "العربية (الإمارات العربية المتحدة)",
			ArYe => "العربية (اليمن)",
			HyAm => "Հայերեն (Հայաստան)",
			AsIn => "অসমীয়া (ভাৰত)",
			AzCyrlAz => "Азәрбајҹан (Азәрбајҹан)",
			AzLatnAz => "Azərbaycan (Azərbaycan)",
			BnBd => "বাংলা (বাংলাদেশ)",
			BnIn => "বাংলা (ভারত)",
			BaRu => "Башҡорт теле (Россия)",
			EuEs => "Euskara (Espainia)",
			BeBy => "Беларуская (Беларусь)",
			BsCyrlBa => "Босански (Босна и Херцеговина)",
			BsLatnBa => "Bosanski (Bosna i Hercegovina)",
			BrFr => "Brezhoneg (Frañs)",
			BgBg => "Български (България)",
			MyMm => "မြန်မာ (မြန်မာ)",
			CaEs => "Català (Espanya)",
			TzmArabMa => "ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵓⵎⵓⵔ ⵏ ⵎⵖⵔⵉⴱ)",
			KuArabIq => "کوردی (عێراق)",
			ChrCherUs => "ᏣᎳᎩ (ᎠᎹᏰᏟ)",
			ZhCn => "简体中文 (中华人民共和国)",
			ZhSg => "简体中文 (新加坡)",
			ZhHk => "繁體中文 (香港特别行政区)",
			ZhMo => "繁體中文 (澳门特别行政区)",
			ZhTw => "繁體中文 (台湾)",
			CoFr => "Corsu (Francia)",
			HrHr => "Hrvatski (Hrvatska)",
			HrBa => "Hrvatski (Bosna i Hercegovina)",
			CsCz => "Čeština (Česká republika)",
			DaDk => "Dansk (Danmark)",
			PrsAf => "دری (افغانستان)",
			DvMv => "ދިވެހިބަސް (ދިވެހި)",
			NlBe => "Nederlands (België)",
			NlNl => "Nederlands (Nederland)",
			DzBt => "རྫོང་ཁ (འབྲུག)",
			EnAu => "English (Australia)",
			EnBz => "English (Belize)",
			EnCa => "English (Canada)",
			En029 => "English (Caribbean)",
			EnHk => "English (Hong Kong)",
			EnIn => "English (India)",
			EnIe => "English (Ireland)",
			EnJm => "English (Jamaica)",
			EnMy => "English (Malaysia)",
			EnNz => "English (New Zealand)",
			EnPh => "English (Republic of the Philippines)",
			EnSg => "English (Singapore)",
			EnZa => "English (South Africa)",
			EnTt => "English (Trinidad and Tobago)",
			EnAe => "English (United Arab Emirates)",
			EnGb => "English (United Kingdom)",
			EnUs => "English (United States)",
			EnZw => "English (Zimbabwe)",
			EtEe => "Eesti (Eesti)",
			FoFo => "Føroyskt (Føroyar)",
			FilPh => "Filipino (Pilipinas)",
			FiFi => "Suomi (Suomi)",
			FrBe => "Français (Belgique)",
			FrCi => "Français (Côte d’Ivoire)",
			FrCm => "Français (Cameroun)",
			FrCa => "Français (Canada)",
			Fr029 => "Français (Caraïbes)",
			FrCd => "Français (Congo, RDC)",
			FrFr => "Français (France)",
			FrHt => "Français (Haïti)",
			FrLu => "Français (Luxembourg)",
			FrMl => "Français (Mali)",
			FrMa => "Français (Maroc)",
			FrMc => "Français (Principauté de Monaco)",
			FrRe => "Français (Réunion)",
			FrSn => "Français (Sénégal)",
			FrCh => "Français (Suisse)",
			FyNl => "Frysk (Nederlân)",
			FfLatnNg => "Pulaar (Nigeria)",
			FfLatnSn => "Pulaar (Senegaal)",
			GlEs => "Galego (España)",
			KaGe => "ქართული (საქართველო)",
			DeAt => "Deutsch (Österreich)",
			DeDe => "Deutsch (Deutschland)",
			DeLi => "Deutsch (Liechtenstein)",
			DeLu => "Deutsch (Luxemburg)",
			DeCh => "Deutsch (Schweiz)",
			ElGr => "Ελληνικά (Ελλάδα)",
			KlGl => "Kalaallisut (Kalaallit Nunaat)",
			GnPy => "Avañe'ẽ (Paraguái)",
			GuIn => "ગુજરાતી (ભારત)",
			HaLatnNg => "Hausa (Najeriya)",
			HawUs => "ʻŌlelo Hawaiʻi (ʻAmelika Hui Pū ʻIa)",
			HeIl => "עברית (ישראל)",
			HiIn => "हिन्दी (भारत)",
			HuHu => "Magyar (Magyarország)",
			IsIs => "Íslenska (Ísland)",
			IgNg => "Igbo (Naịjịrịa)",
			IdId => "Bahasa Indonesia (Indonesia)",
			IuLatnCa => "Inuktitut (Kanata)",
			IuCansCa => "ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)",
			GaIe => "Gaeilge (Éire)",
			ItIt => "Italiano (Italia)",
			ItCh => "Italiano (Svizzera)",
			JaJp => "日本語 (日本)",
			KnIn => "ಕನ್ನಡ (ಭಾರತ)",
			KrLatnNg => "Kanuri (Nigeria)",
			KsDevaIn => "कश्मीरी (देवनागरी, भारत)",
			KkKz => "Қазақ (Қазақстан)",
			KmKh => "ភាសាខ្មែរ (កម្ពុជា)",
			QucLatnGt => "K'iche' (Guatemala)",
			RwRw => "Kinyarwanda (Rwanda)",
			SwKe => "Kiswahili (Kenya)",
			KokIn => "कोंकणी (भारत)",
			KoKr => "한국어 (대한민국)",
			KyKg => "Кыргызча (Кыргызстан)",
			LoLa => "ລາວ (ປະເທດລາວ)",
			LaVa => "Latina (Civitas Vaticana)",
			LvLv => "Latviešu (Latvija)",
			LtLt => "Lietuvių (Lietuva)",
			DsbDe => "Dolnoserbšćina (Nimska)",
			LbLu => "Lëtzebuergesch (Lëtzebuerg)",
			MkMk => "Македонски (Северна Македонија)",
			MsBn => "Melayu (Brunei Darussalam)",
			MsMy => "Melayu (Malaysia)",
			MlIn => "മലയാളം (ഇന്ത്യ)",
			MtMt => "Malti (Malta)",
			MiNz => "Māori (Aotearoa)",
			ArnCl => "Mapudungun (Chile)",
			MrIn => "मराठी (भारत)",
			MohCa => "Kanien’kéha (Canada)",
			MnMn => "Монгол (Монгол)",
			MnMongMn => "ᠮᠣᠩᠭᠣᠯ (ᠮᠣᠩᠭᠣᠯ)",
			NeIn => "नेपाली (भारत)",
			NeNp => "नेपाली (नेपाल)",
			NbNo => "Norsk bokmål (Norge)",
			NnNo => "Norsk nynorsk (Norge)",
			OcFr => "Occitan (França)",
			OrIn => "ଓଡ଼ିଆ (ଭାରତ)",
			OmEt => "Afaan Oromoo (Itoophiyaa)",
			PsAf => "پښتو (افغانستان)",
			FaIr => "فارسی (ایران)",
			PlPl => "Polski (Polska)",
			PtBr => "Português (Brasil)",
			PtPt => "Português (Portugal)",
			PaIn => "ਪੰਜਾਬੀ (ਭਾਰਤ)",
			PaArabPk => "پنجابی (پاکستان)",
			QuzBo => "Runasimi (Bolivia)",
			QuzEc => "Runasimi (Ecuador)",
			QuzPe => "Runasimi (Perú)",
			RoMd => "Română (Moldova)",
			RoRo => "Română (România)",
			RmCh => "Rumantsch (Svizra)",
			RuMd => "Русский (Молдова)",
			RuRu => "Русский (Россия)",
			SahRu => "Саха (Россия)",
			SmnFi => "Anarâškielâ (Suomâ)",
			SmjNo => "Julevsámegiella (Norga)",
			SmjSe => "Julevsámegiella (Svierik)",
			SeFi => "Davvisámegiella (Suopma)",
			SeNo => "Davvisámegiella (Norga)",
			SeSe => "Davvisámegiella (Svierik)",
			SmsFi => "Skolt sámegiella (Suomâ)",
			SmaNo => "Åarjelsaemien gïele (Nöörje)",
			SmaSe => "Åarjelsaemien gïele (Sveerje)",
			SaIn => "संस्कृतम् (भारत)",
			GdGb => "Gàidhlig (An Rìoghachd Aonaichte)",
			SrCyrlBa => "Српски (Ћирилица, Босна и Херцеговина)",
			SrCyrlMe => "Српски (Ћирилица, Црна Гора)",
			SrCyrlRs => "Српски (Ћирилица, Србија)",
			SrLatnBa => "Srpski (Latinica, Bosna i Hercegovina)",
			SrLatnMe => "Srpski (Latinica, Crna Gora)",
			SrLatnRs => "Srpski (Latinica, Srbija)",
			NsoZa => "Sesotho sa Leboa (Afrika Borwa)",
			TnBw => "Setswana (Botswana)",
			TnZa => "Setswana (Aforika Borwa)",
			SdArabPk => "سنڌي (پاکستان)",
			SiLk => "සිංහල (ශ්‍රී ලංකාව)",
			SkSk => "Slovenčina (Slovensko)",
			SlSi => "Slovenščina (Slovenija)",
			SoSo => "Soomaali (Soomaaliya)",
			StZa => "Sesotho (Afrika Borwa)",
			EsAr => "Español (Argentina)",
			EsVe => "Español (República Bolivariana de Venezuela)",
			EsBo => "Español (Bolivia)",
			EsCl => "Español (Chile)",
			EsCo => "Español (Colombia)",
			EsCr => "Español (Costa Rica)",
			EsCu => "Español (Cuba)",
			EsDo => "Español (República Dominicana)",
			EsEc => "Español (Ecuador)",
			EsSv => "Español (El Salvador)",
			EsGt => "Español (Guatemala)",
			EsHn => "Español (Honduras)",
			Es419 => "Español (Latinoamérica)",
			EsMx => "Español (México)",
			EsNi => "Español (Nicaragua)",
			EsPa => "Español (Panamá)",
			EsPy => "Español (Paraguay)",
			EsPe => "Español (Perú)",
			EsPr => "Español (Puerto Rico)",
			EsEs => "Español (España)",
			EsUs => "Español (Estados Unidos)",
			EsUy => "Español (Uruguay)",
			SvFi => "Svenska (Finland)",
			SvSe => "Svenska (Sverige)",
			SyrSy => "ܣܘܪܝܝܐ (ܣܘܪܝܐ)",
			TgCyrlTj => "Тоҷикӣ (Тоҷикистон)",
			TzmLatnDz => "Tamaziɣt (Djazaïr)",
			TaIn => "தமிழ் (இந்தியா)",
			TaLk => "தமிழ் (இலங்கை)",
			TtRu => "Татар (Россия)",
			TeIn => "తెలుగు (భారతదేశం)",
			ThTh => "ไทย (ประเทศไทย)",
			BoCn => "བོད་ཡིག (རྒྱ་ནག)",
			TiEr => "ትግርኛ (ኤርትራ)",
			TiEt => "ትግርኛ (ኢትዮጵያ)",
			TsZa => "Xitsonga (Afrika Dzonga)",
			TrTr => "Türkçe (Türkiye)",
			TkTm => "Türkmen (Türkmenistan)",
			UkUa => "Українська (Україна)",
			HsbDe => "Hornjoserbšćina (Němska)",
			UrIn => "اردو (بھارت)",
			UrPk => "اردو (پاکستان)",
			UgCn => "ئۇيغۇرچە (جۇڭگو)",
			UzCyrlUz => "Ўзбек (Ўзбекистон)",
			UzLatnUz => "Oʻzbek (Oʻzbekiston)",
			CaEsValencia => "Valencià (Espanya)",
			VeZa => "Tshivenḓa (Afurika Tshipembe)",
			ViVn => "Tiếng Việt (Việt Nam)",
			CyGb => "Cymraeg (Y Deyrnas Unedig)",
			WoSn => "Wolof (Senegaal)",
			XhZa => "isiXhosa (uMzantsi Afrika)",
			IiCn => "ꆈꌠꁱꂷ (ꍏꇩꉙꏱꅉꑤ꓄ꂱꇩ)",
			Yi001 => "ייִדיש (וועלט)",
			YoNg => "Èdè Yorùbá (Nàìjíríà)",
			ZuZa => "isiZulu (iNingizimu Afrika)",
		}
	}
}
#[cfg(feature = "serde")]
impl Serialize for Language {
	fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
	where
		S: Serializer,
	{
		serializer.serialize_str(self.as_tag())
	}
}
#[cfg(feature = "serde")]
impl<'de> Deserialize<'de> for Language {
	fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
	where
		D: Deserializer<'de>,
	{
		let tag = String::deserialize(deserializer)?;

		Language::from_tag(&tag).ok_or_else(|| Error::unknown_variant(&tag, &[]))
	}
}
